-- Wedding-type tags and listing order for the venue listing.
--
-- /hotel-listing and the 53 city index pages filter and page through venues.
-- Both read site-public/data/hotel-listing-data.json, a generated file no admin
-- edit could reach: renaming a venue, changing its thumbnail, retagging it or
-- unpublishing it changed the venue page and left the listing on the old copy.
--
-- Two things in that file were not derivable from any column and are added here.
--
-- The type ids are load-bearing. They are the `wedding_types[]=N` values in the filter
-- checkboxes and in every shared or indexed listing URL, so they keep the numbers
-- the original site gave them rather than being renumbered.
CREATE TABLE "venue_types" (
	"id" integer PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"label" text NOT NULL,
	"published" integer DEFAULT 1 NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "venue_types_slug_idx" ON "venue_types" USING btree ("slug");
--> statement-breakpoint
-- Seeded in the order the filter list already showed them: alphabetical by label.
INSERT INTO "venue_types" ("id", "slug", "label", "published", "position") VALUES
	(3, 'city', 'City Wedding', 1, 0),
	(2, 'destination', 'Destination Wedding', 1, 1),
	(7, 'intimate', 'Intimate Wedding', 1, 2),
	(6, 'luxury', 'Luxury Wedding', 1, 3),
	(5, 'palace', 'Palace Wedding', 1, 4),
	(4, 'resort', 'Resort Wedding', 1, 5)
ON CONFLICT ("id") DO NOTHING;
--> statement-breakpoint
ALTER TABLE "hotels" ADD COLUMN "wedding_types" text DEFAULT '[]' NOT NULL;
--> statement-breakpoint
-- Where a venue sits in the listing. The generated file opened with six chosen
-- venues and then followed no rule the rest of the way, so the order is data,
-- not something to recompute. A venue added later defaults to the end.
ALTER TABLE "hotels" ADD COLUMN "listing_position" integer DEFAULT 9999 NOT NULL;
--> statement-breakpoint
-- Keyed by the calculator hotel id the venue already joins through. Guarded on
-- the columns still holding their defaults, so a re-run cannot undo an edit.
UPDATE "hotels" AS h SET "wedding_types" = v.types, "listing_position" = v.position
FROM (VALUES
	('40', '["destination","intimate","palace"]', 0),
	('9', '["destination","luxury","palace"]', 1),
	('47', '["destination","intimate","palace"]', 2),
	('32', '["destination","luxury"]', 3),
	('12', '["destination","intimate","luxury","palace"]', 4),
	('21', '["destination","luxury"]', 5),
	('155', '["destination","intimate","luxury","resort"]', 6),
	('168', '["destination","luxury"]', 7),
	('169', '["destination","luxury"]', 8),
	('48', '["destination","luxury"]', 9),
	('63', '["destination","luxury","palace"]', 10),
	('170', '["destination","intimate","palace"]', 11),
	('171', '["destination","luxury"]', 12),
	('156', '["destination","intimate","luxury"]', 13),
	('45', '["destination","luxury","palace"]', 14),
	('166', '["destination","luxury"]', 15),
	('309', '["city","destination","luxury"]', 16),
	('305', '["city","destination","luxury"]', 17),
	('262', '["city","destination","luxury"]', 18),
	('280', '["city","destination","luxury"]', 19),
	('133', '["destination","intimate","palace"]', 20),
	('144', '["destination","luxury"]', 21),
	('131', '["destination","luxury","resort"]', 22),
	('130', '["destination","luxury"]', 23),
	('129', '["destination","luxury"]', 24),
	('167', '["destination","intimate","palace"]', 25),
	('91', '["destination","luxury"]', 26),
	('388', '["city","destination","luxury"]', 27),
	('381', '["city","destination","luxury"]', 28),
	('81', '["city","destination","luxury"]', 29),
	('267', '["city","destination","luxury"]', 30),
	('78', '["city","destination","luxury","resort"]', 31),
	('287', '["city","destination","luxury"]', 32),
	('284', '["city","destination","luxury"]', 33),
	('82', '["city","destination","luxury"]', 34),
	('264', '["city","destination","luxury"]', 35),
	('77', '["city","destination","luxury","palace"]', 36),
	('80', '["city","destination","luxury"]', 37),
	('241', '["destination","luxury"]', 38),
	('242', '["destination","luxury"]', 39),
	('239', '["destination","luxury","resort"]', 40),
	('59', '["city","destination","luxury","palace"]', 41),
	('60', '["city","destination","luxury","palace"]', 42),
	('139', '["city","destination","luxury","palace"]', 43),
	('138', '["city","destination","luxury","palace"]', 44),
	('61', '["city","destination","intimate","luxury","palace"]', 45),
	('293', '["city","destination","luxury"]', 46),
	('294', '["city","destination","luxury"]', 47),
	('84', '["city","destination","luxury"]', 48),
	('90', '["city","destination","luxury"]', 49),
	('291', '["city","destination","luxury"]', 50),
	('292', '["city","destination","luxury"]', 51),
	('289', '["city","destination","luxury"]', 52),
	('88', '["city","destination","luxury","palace"]', 53),
	('302', '["destination","intimate","resort"]', 54),
	('301', '["destination","intimate","resort"]', 55),
	('439', '["destination","luxury"]', 56),
	('67', '["destination","luxury","resort"]', 57),
	('137', '["destination","intimate","luxury","resort"]', 58),
	('154', '["destination","luxury"]', 59),
	('230', '["city","destination","luxury"]', 60),
	('103', '["city","destination","luxury","resort"]', 61),
	('270', '["city","destination","luxury"]', 62),
	('372', '["city","destination","luxury","palace","resort"]', 63),
	('97', '["city","destination","luxury"]', 64),
	('268', '["city","destination","luxury"]', 65),
	('368', '["city","destination","luxury","resort"]', 66),
	('357', '["city","destination","luxury"]', 67),
	('369', '["city","destination","resort"]', 68),
	('232', '["city","destination","luxury"]', 69),
	('306', '["city","destination","luxury"]', 70),
	('370', '["city","destination","luxury","resort"]', 71),
	('17', '["destination","luxury"]', 72),
	('353', '["destination","luxury","resort"]', 73),
	('22', '["destination","luxury","resort"]', 74),
	('23', '["destination","luxury"]', 75),
	('18', '["destination","luxury","resort"]', 76),
	('157', '["destination","luxury"]', 77),
	('352', '["destination","luxury"]', 78),
	('351', '["destination","luxury","resort"]', 79),
	('158', '["destination","luxury","resort"]', 80),
	('356', '["destination","luxury","palace"]', 81),
	('437', '["destination","luxury"]', 82),
	('175', '["destination","luxury","resort"]', 83),
	('295', '["destination","luxury"]', 84),
	('275', '["destination","intimate","luxury","palace"]', 85),
	('285', '["city","destination","luxury"]', 86),
	('114', '["city","destination","luxury"]', 87),
	('288', '["city","destination","luxury"]', 88),
	('367', '["city","destination","luxury"]', 89),
	('115', '["city","destination","luxury"]', 90),
	('290', '["city","destination","luxury"]', 91),
	('310', '["city","destination","luxury"]', 92),
	('296', '["city","destination","luxury"]', 93),
	('303', '["city","destination","luxury"]', 94),
	('112', '["city","destination","intimate","luxury","palace"]', 95),
	('117', '["city","destination","luxury"]', 96),
	('118', '["city","destination","luxury"]', 97),
	('300', '["destination","luxury"]', 98),
	('298', '["destination","luxury"]', 99),
	('299', '["destination","luxury","palace"]', 100),
	('297', '["destination"]', 101),
	('181', '["destination","luxury","resort"]', 102),
	('148', '["destination","luxury","palace"]', 103),
	('245', '["destination","intimate","luxury","resort"]', 104),
	('197', '["destination","luxury","palace"]', 105),
	('187', '["destination","luxury"]', 106),
	('42', '["destination","luxury"]', 107),
	('27', '["destination","luxury"]', 108),
	('183', '["destination","luxury","palace"]', 109),
	('192', '["destination","luxury"]', 110),
	('125', '["destination","luxury","palace"]', 111),
	('162', '["destination","intimate","luxury","palace"]', 112),
	('161', '["destination","intimate","palace"]', 113),
	('49', '["destination","luxury","resort"]', 114),
	('127', '["destination","intimate","luxury"]', 115),
	('126', '["destination","intimate","luxury","palace"]', 116),
	('54', '["destination","intimate"]', 117),
	('55', '["destination","intimate"]', 118),
	('236', '["destination","intimate","resort"]', 119),
	('53', '["destination","intimate","luxury","resort"]', 120),
	('58', '["destination","intimate","luxury","resort"]', 121),
	('234', '["destination","intimate","resort"]', 122),
	('56', '["destination","intimate","luxury"]', 123),
	('57', '["destination","intimate","luxury"]', 124),
	('44', '["destination","intimate","palace"]', 125),
	('31', '["destination","intimate","luxury"]', 126),
	('145', '["destination","intimate","palace"]', 127),
	('26', '["destination","intimate","luxury","palace"]', 128),
	('25', '["destination","intimate","palace"]', 129),
	('346', '["destination","intimate","palace","resort"]', 130),
	('30', '["destination","luxury"]', 131),
	('377', '["destination","luxury","palace"]', 132),
	('92', '["destination","intimate","luxury","resort"]', 133),
	('93', '["destination","intimate","resort"]', 134),
	('315', '["destination","intimate","luxury","resort"]', 135),
	('358', '["destination","intimate","palace","resort"]', 136),
	('374', '["destination","intimate","luxury","resort"]', 137),
	('87', '["destination","intimate","luxury","resort"]', 138),
	('317', '["destination","luxury","resort"]', 139),
	('385', '["destination","intimate","luxury","palace"]', 140),
	('276', '["destination","intimate","luxury"]', 141),
	('85', '["destination","luxury"]', 142),
	('277', '["destination","luxury"]', 143),
	('314', '["destination","luxury"]', 144),
	('279', '["city","destination","luxury"]', 145),
	('383', '["city","destination","luxury"]', 146),
	('95', '["city","destination","luxury"]', 147),
	('318', '["city","destination","luxury"]', 148),
	('278', '["city","destination","luxury"]', 149),
	('86', '["destination","luxury","resort"]', 150),
	('379', '["destination","luxury"]', 151),
	('281', '["destination","luxury"]', 152),
	('263', '["destination","luxury","palace"]', 153),
	('316', '["city","destination","luxury"]', 154),
	('376', '["city","destination","luxury"]', 155),
	('109', '["city","destination","luxury"]', 156),
	('271', '["city","destination","luxury"]', 157),
	('272', '["city","destination","intimate"]', 158),
	('101', '["city","destination","luxury"]', 159),
	('273', '["city","destination","luxury"]', 160),
	('111', '["city","destination","luxury"]', 161),
	('274', '["city","destination","luxury","resort"]', 162),
	('311', '["city","destination","luxury"]', 163),
	('380', '["city","destination","luxury"]', 164),
	('102', '["city","destination","luxury"]', 165),
	('64', '["destination","luxury"]', 166),
	('65', '["destination","luxury","resort"]', 167),
	('249', '["destination","intimate","palace","resort"]', 168),
	('52', '["destination","intimate","luxury"]', 169),
	('359', '["city","destination","luxury"]', 170),
	('72', '["city","destination","luxury"]', 171),
	('386', '["city","destination","luxury"]', 172),
	('307', '["city","destination","luxury"]', 173),
	('283', '["city","destination","luxury"]', 174),
	('70', '["city","destination","luxury"]', 175),
	('73', '["city","destination","luxury"]', 176),
	('134', '["destination","intimate","luxury","resort"]', 177),
	('136', '["destination","intimate","resort"]', 178),
	('164', '["destination","intimate","resort"]', 179),
	('172', '["destination","luxury"]', 180),
	('173', '["destination","luxury","resort"]', 181),
	('153', '["destination","palace"]', 182),
	('387', '["destination","intimate","palace"]', 183),
	('345', '["destination","intimate","luxury"]', 184),
	('378', '["destination","intimate","resort"]', 185),
	('66', '["destination","intimate","luxury","resort"]', 186),
	('68', '["destination","luxury","resort"]', 187),
	('69', '["destination","intimate","luxury","resort"]', 188),
	('282', '["destination","luxury"]', 189),
	('89', '["destination","luxury"]', 190),
	('149', '["destination","luxury"]', 191),
	('342', '["destination","intimate","palace"]', 192),
	('151', '["destination","luxury"]', 193),
	('349', '["destination","intimate","resort"]', 194),
	('343', '["destination","palace","resort"]', 195),
	('341', '["destination","intimate","palace","resort"]', 196),
	('34', '["destination","luxury"]', 197),
	('350', '["destination","luxury","palace","resort"]', 198),
	('344', '["destination","intimate","palace"]', 199),
	('150', '["destination","luxury","palace","resort"]', 200),
	('308', '["city","destination","luxury"]', 201),
	('98', '["city","destination","luxury","resort"]', 202),
	('260', '["city","destination","luxury"]', 203),
	('269', '["city","destination","luxury","palace"]', 204),
	('375', '["city","destination","luxury","palace","resort"]', 205),
	('319', '["city","destination","intimate","luxury"]', 206),
	('104', '["city","destination","luxury"]', 207),
	('258', '["city","destination","luxury","palace"]', 208),
	('107', '["city","destination","luxury"]', 209),
	('259', '["city","destination","intimate","luxury"]', 210),
	('100', '["city","destination","intimate","luxury","resort"]', 211),
	('108', '["city","destination","luxury"]', 212),
	('313', '["city","destination","intimate","luxury"]', 213),
	('20', '["destination","luxury","resort"]', 214),
	('354', '["destination","luxury","palace","resort"]', 215),
	('355', '["destination","luxury","resort"]', 216),
	('384', '["destination","luxury","resort"]', 217),
	('14', '["destination","luxury","resort"]', 218),
	('29', '["destination","luxury","resort"]', 219),
	('116', '["city","destination","luxury"]', 220),
	('286', '["city","destination","luxury"]', 221),
	('35', '["destination","intimate","luxury","palace"]', 222),
	('124', '["destination","luxury","resort"]', 223),
	('179', '["destination","intimate","luxury"]', 224),
	('186', '["destination","luxury","palace"]', 225),
	('184', '["destination","luxury"]', 226),
	('248', '["destination","palace","resort"]', 227),
	('36', '["destination","intimate","luxury"]', 228),
	('185', '["destination","luxury","palace","resort"]', 229),
	('37', '["destination","intimate","palace"]', 230),
	('246', '["destination","intimate"]', 231),
	('182', '["destination","luxury","palace"]', 232),
	('146', '["destination","luxury","palace","resort"]', 233),
	('194', '["destination","intimate","palace","resort"]', 234),
	('193', '["destination","intimate","palace"]', 235),
	('28', '["destination","luxury","palace"]', 236),
	('180', '["destination","intimate","luxury","palace"]', 237),
	('247', '["destination","luxury","palace","resort"]', 238),
	('178', '["destination","luxury","resort"]', 239),
	('312', '["city","destination","luxury"]', 240),
	('382', '["city","destination","luxury"]', 241),
	('371', '["city","destination","luxury"]', 242),
	('96', '["city","destination","luxury"]', 243),
	('99', '["city","destination","luxury","palace"]', 244),
	('106', '["city","destination","luxury","resort"]', 245),
	('105', '["city","destination","luxury"]', 246),
	('19', '["destination","luxury"]', 247),
	('373', '["destination","intimate","resort"]', 248),
	('43', '["destination","luxury","resort"]', 249),
	('33', '["destination","intimate","luxury","palace"]', 250),
	('24', '["destination","intimate","luxury","palace","resort"]', 251),
	('152', '["destination","luxury"]', 252),
	('348', '["destination","luxury"]', 253),
	('257', '["destination","intimate","luxury","palace"]', 254),
	('38', '["destination","intimate","luxury","palace"]', 255),
	('347', '["destination","luxury"]', 256),
	('41', '["destination","luxury"]', 257),
	('39', '["destination","luxury","resort"]', 258)
) AS v(external_id, types, position)
WHERE h.external_hotel_id = v.external_id
  AND h.wedding_types = '[]' AND h.listing_position = 9999;
